# Generated by Django 4.1.7 on 2023-05-10 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0004_delete_join"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="PID", field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="key",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_price",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_platform",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="ticket_time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
