# Generated by Django 4.1.7 on 2023-05-10 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0005_alter_order_pid_alter_order_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="PID", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="key",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_platform",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="ticket_time",
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
