# Generated by Django 4.1.7 on 2023-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0006_alter_order_pid_alter_order_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ticket_time",
            field=models.DateTimeField(null=True),
        ),
    ]
